version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres

    restart: always

    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - TZ=America/Fortaleza

   
    
  backend:
    container_name: backend
  
    depends_on:
        - postgres

    build: Docker_backend/

    ports:
      - 3000:3000

    command:
        bash -c "npx prisma migrate dev --name init &&  sleep 2 && npm run dev" 

  




